default_ignores: false
fix: true
format: progress
parallel: true

ignore:
  - "db/schema.rb"
  - "vendor/**/*"
  - "test/**/*":
      - Layout/AlignHash
  - "**/*":
      - Layout/ArgumentAlignment
      - Layout/ArrayAlignment
      - Layout/BlockAlignment
      - Layout/ClosingHeredocIndentation
      - Layout/FirstArgumentIndentation
      - Layout/MultilineMethodCallIndentation
      - Layout/MultilineOperationIndentation
      - Layout/SpaceInsideHashLiteralBraces
      - Lint/AssignmentInCondition
      - Lint/ShadowedException
      - Style/MultilineMemoization
      - Style/RescueStandardError
