# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{config_reader}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Moen"]
  s.date = %q{2010-02-24}
  s.description = %q{Provides a way to manage environment specific configuration settings.}
  s.email = %q{michael@underpantsgnome.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "History.txt",
     "License.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "config_reader.gemspec",
     "lib/config_reader.rb",
     "spec/config_reader_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/test_config.rb",
     "spec/test_config.yml"
  ]
  s.homepage = %q{http://github.com/UnderpantsGnome/config_reader-gem}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Provides a way to manage environment specific configuration settings.}
  s.test_files = [
    "spec/config_reader_spec.rb",
     "spec/spec_helper.rb",
     "spec/test_config.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

